spring:
  config:
    activate:
      on-profile: local
token:
  expiration_time: 864000000
  secret: gateway_config_local

gateway:
  ip: 127.0.0.1

---

spring:
  config:
    activate:
      on-profile: prod
token:
  expiration_time: 864000000
  secret: gateway_config_prod

gateway:
  ip: 127.0.0.1