spring:
  config:
    activate:
      on-profile: local
token:
  expiration_time: 864000000
  secret: value_sample_service2_local_change

---

spring:
  config:
    activate:
      on-profile: prod
token:
  expiration_time: 864000000
  secret: value_sample_service2_prod_change
