spring:
  profiles: prod
token:
  expiration_time: 864000000
  secret: value_sample2_prod
---
spring:
  profiles: dev
token:
  expiration_time: 864000000
  secret: value_sample2_dev
---
spring:
  profiles: local
token:
  expiration_time: 864000000
  secret: value_sample2_local
