spring:
  config:
    activate:
      on-profile: local
token:
  expiration_time: 864000000
  secret: value_sample_service1_local_change_222

---

spring:
  config:
    activate:
      on-profile: prod
token:
  expiration_time: 864000000
  secret: value_sample_service1_prod_change_222
